-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: enhancement_jobs table
-- Run in Supabase SQL editor
-- ─────────────────────────────────────────────────────────────────────────────
--
-- Stores the state of each background enhancement job.
-- The API route creates a row and returns the job ID immediately.
-- The background process updates status as it progresses.
-- The client polls /api/enhance/status?jobId=xxx until complete or failed.
--

CREATE TABLE IF NOT EXISTS public.enhancement_jobs (
  id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  asset_id         UUID         NOT NULL REFERENCES public.uploaded_assets(id) ON DELETE CASCADE,
  listing_id       UUID         NOT NULL REFERENCES public.listings(id)        ON DELETE CASCADE,

  -- Pipeline status
  status           TEXT         NOT NULL DEFAULT 'uploading'
                   CHECK (status IN ('uploading','removing_bg','enhancing','compositing','complete','failed')),

  -- Result — populated on success
  result_path      TEXT,        -- Supabase storage path of the enhanced image
  result_url       TEXT,        -- signed URL (may expire — regenerated by status endpoint)
  result_width_px  INTEGER,
  result_height_px INTEGER,
  result_bytes     INTEGER,

  -- Error — populated on failure
  error_message    TEXT,

  created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Index for polling queries
CREATE INDEX IF NOT EXISTS idx_enhancement_jobs_listing
  ON public.enhancement_jobs(listing_id);

CREATE INDEX IF NOT EXISTS idx_enhancement_jobs_asset
  ON public.enhancement_jobs(asset_id);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_enhancement_jobs_updated_at ON public.enhancement_jobs;
CREATE TRIGGER trg_enhancement_jobs_updated_at
  BEFORE UPDATE ON public.enhancement_jobs
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- RLS: users can only see jobs for their own listings
ALTER TABLE public.enhancement_jobs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own enhancement jobs"
  ON public.enhancement_jobs FOR SELECT
  USING (
    listing_id IN (
      SELECT id FROM public.listings WHERE session_id = auth.uid()::text
    )
  );

-- ─────────────────────────────────────────────────────────────────────────────
-- Add to existing tables (idempotent — safe to re-run)
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.listings
  ADD COLUMN IF NOT EXISTS source_app   TEXT,
  ADD COLUMN IF NOT EXISTS webhook_url  TEXT,
  ADD COLUMN IF NOT EXISTS seo_assessment JSONB;

ALTER TABLE public.marketplace_drafts
  ADD COLUMN IF NOT EXISTS seo_score       SMALLINT,
  ADD COLUMN IF NOT EXISTS title_keywords  TEXT[],
  ADD COLUMN IF NOT EXISTS item_specifics  JSONB,
  ADD COLUMN IF NOT EXISTS posted_url      TEXT,
  ADD COLUMN IF NOT EXISTS posted_at       TIMESTAMPTZ;

ALTER TABLE public.uploaded_assets
  ADD COLUMN IF NOT EXISTS source_url  TEXT;

CREATE INDEX IF NOT EXISTS idx_listings_source_app
  ON public.listings(source_app)
  WHERE source_app IS NOT NULL;
